### ISSUE TITLE
Show information on existing keyboard shortcuts

### ISSUE THREAD

**Issue by andbue** [OCR4all/LAREX#111]
A small popover/modal/alert showing existing shortcuts on button click or key press F1 would be helpful!

**Comment by NesbiDevelopment** [comment]
All functions with shortcuts should now display them in the tooltip of their buttons.

A complete help window is good idea and I'd like to add it in the future.

**Comment by bertsky** [comment]
> All functions with shortcuts should now display them in the tooltip of their buttons.

This naturally does not count for navigation functions like:
- `+` and `-` for page zoom
- cursor keys for page pan
- spacebar for max zoom
- tab for next region

Maybe there are more of these I don't know yet. It would indeed be great to summarize all of them in a help page.

Also, I wonder if there's any shortcut for _next page_ / _previous page_ – `PageUp`/`PageDown` does not work…

**Comment by andbue** [comment]
+1 for the PageUp/PageDown!

**Comment by maxnth** [comment]
>`+` and `-` for page zoom
>cursor keys for page pan
>spacebar for max zoom

This are already shown next to the corresponding icon.
See e.g.
![Screenshot_20200605_124612](https://user-images.githubusercontent.com/33344081/83868157-b0820f00-a72a-11ea-9da5-3b3a91da2c83.png)

>tab for next region
For cases like this an overview would really be useful.
Maybe just adding a PDF with all shortcuts + explanation to our `getting_started` repo would suffice? Or would it be a big improvement to let the user access the information directly in Larex in your opinion?

**Comment by maxnth** [comment]
Navigating to the next/previous page via PageUp/PageDown Keys was added in #191 and is now available in the dev branch

**Comment by bertsky** [comment]
> This are already shown next to the corresponding icon.

Oh, overlooked that – self-explanatory is best of course.

> Maybe just adding a PDF with all shortcuts + explanation to our `getting_started` repo would suffice?

Yes, that would be sufficient IMHO.
