### ISSUE TITLE
Feature request: automatic execution for multiple pages

### ISSUE THREAD

**Issue by otaviodeon** [OCR4all/LAREX#127]
When dealing with a large number of documents/pages, an automatic execution of the segmentation/download of the resulting XML for those multiple pages (e.g via command line) would be useful. 
Automating the proccessing of multiple pages, maintaining the parameters or not, would save a considerable amount of time.

**Comment by maxnth** [comment]
basic batch segmentation added in 3b8fa8a91126d8371a568b79e92164ae10c90cc1

**Comment by maxnth** [comment]
added in release [0.5.0](https://github.com/OCR4all/LAREX/releases/tag/0.5.0)
