### ISSUE TITLE
Hide tabs when only one mode is accessible

### ISSUE THREAD

**Issue by andbue** [OCR4all/LAREX#133]
E.g. in gui.js, this.setAccessibleModes:
```js
if (modes.length === 1){
    $(".tabs").addClass("hide")
}
```

**Comment by NesbiDevelopment** [comment]
Hello, thank you for that suggestion.
I will look into it and check how the css framework behaves if we hide the tabs completely.

**Comment by NesbiDevelopment** [comment]
Looks and works well.
Will be added to the next update.

Thank you for your suggestion.

**Comment by NesbiDevelopment** [comment]
Now live on master:
fd9d5adc11b273258539d869f949edb1bbcc1290
