### ISSUE TITLE
 BUILD FAILURE

### ISSUE THREAD

**Issue by jsbien** [OCR4all/LAREX#140]
Debian buster:

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jsbien/LAREX/src/main/java/com/web/controller/FileController.java:[15,24] package javax.annotation does not exist
[ERROR] /home/jsbien/LAREX/src/main/java/com/web/controller/SegmentationController.java:[10,24] package javax.annotation does not exist
[ERROR] /home/jsbien/LAREX/src/main/java/com/web/controller/FileController.java:[74,10] cannot find symbol
  symbol:   class PostConstruct
  location: class com.web.controller.FileController
[ERROR] /home/jsbien/LAREX/src/main/java/com/web/controller/SegmentationController.java:[54,10] cannot find symbol
  symbol:   class PostConstruct
  location: class com.web.controller.SegmentationController
[INFO] 4 errors

**Comment by NesbiDevelopment** [comment]
Hello, this problem seems to be a problem with java 11+

It should now be fixed:
https://github.com/OCR4all/LAREX/pull/139

**Comment by jsbien** [comment]
Yes, the build is succesful. Thanks!
