### ISSUE TITLE
installation fails with 404

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#159]
I have followed the installation instructions for Linux in the README, which yields no errors and brings me to the point where I should be able to use `http://localhost:8080/Larex` – but this gives me:

```
HTTP ERROR 404

Problem accessing /Larex. Reason:

    Not Found

Powered by Jetty:// 9.4.15.v20190215
```

For reference, this is what I did (again, in accordance with the instructions here):
1. `sudo apt-get install tomcat8 maven openjdk-8-jdk`
2. `git clone https://github.com/OCR4all/LAREX`
3. `mvn clean install -f LAREX/pom.xml`
4. `sudo cp LAREX/target/Larex.war /var/lib/tomcat8/webapps/`
5. `sudo systemctl start tomcat8`

I can see tomcat8 service loaded and active/running. 

In addition to `Larex.war` (owned by `root`), the directory `/var/lib/tomcat8/webapps/` now contains a subdirectory `Larex` (owned by the user `tomcat8`), identical to `LAREX/src/main/webapp`, except for an extra `META-INF` and `WEB-INF/`.

Versions:
- jetty9 9.4.15
- tomcat8 8.5.39
- openjdk-8-jdk 8u232-b09
- maven 3.6.0
- LAREX 229b37e096df910011b7023234e218a3b7148497

(I _can_ see the Jetty9 landing page in the root directory, _Welcome to Jetty 9 on Debian_ etc.)

What now?

**Comment by maxnth** [comment]
Hello @bertsky,
could you try copying the ```LAREX.war``` to ```$JETTY_HOME\webapps``` (or change the default port of either Jetty or Tomact) and report back whether LAREX is accessible afterwards?

My guess would be that (in case there's no mapping between ```/var/lib/tomcat8/webapps/``` and ```$JETTY_HOME\webapps``` or the ```LAREX.war``` wasn't copied to the latter path as well) Jetty doesn't know anything about the LAREX WAR file at ```/var/lib/tomcat8/webapps``` and is "blocking" port 8080 so that the LAREX webapp (deployed to Tomcat) isn't reachable under that port on localhost.

**Comment by bertsky** [comment]
Hi @maxnth, 
thanks for your help!

Indeed, copying `LAREX.war` to `/usr/share/jetty9/webapps/` did the trick.

I must confess, I am a little embarassed to not have noticed myself that jetty is another server competing for 8080 and not even included by your instructions.

Anyway, this was great advice – again, thank you very much.
