### ISSUE TITLE
describe bookpath layout, show informative error

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#160]
When I configure a non-default `bookpath` as described by the [documentation](https://github.com/OCR4all/LAREX#bookpath), I always get this:

```
Ooopps!

That should not have happened!

It seems like the server has mixed something up.

Error code: 500
```

This does not help at all. The server's log then showed several null pointer exceptions, among them `de.uniwue.web.io.FileDatabase.listBookFiles`.

Digging into that, I found that there is sufficient documentation on the expected directory structure [in the sources](https://github.com/OCR4all/LAREX/blob/229b37e096df910011b7023234e218a3b7148497/src/main/java/de/uniwue/web/io/FileDatabase.java#L22). But I cannot browse that API documentation, and IMHO this particular piece of knowledge crucially belongs into the user documentation as well.

Also, IIUC, a bookpath must always be a flat directory with certain file name patterns to separate pages but group annotations. This strikes me as overly restrictive. Perhaps this can be generalized to layouts like those we have in [OCR-D](https://ocr-d.github.io/mets) – subdirectories for annotations, PAGE-XML's `@imageFilename` relative to the root directory of the book?

So please,
1. document the expected directory structure for `bookpath` in the README (or similar)
2. catch the null pointer exception and give a meaningful error message
3. [optionally] generalize expectation to non-flat directory structure

**Comment by bertsky** [comment]
There's more to it. I cannot even get (my absolute path of the distribution's) `src/main/webapp/resources/books/` to work. I can only see the `LIBRARY` view without "oops" when I _don't_ set anything for `bookpath`. (It's always the same null pointer exception.)

**Comment by maxnth** [comment]
Hello @bertsky,
thanks for your feedback and please excuse the problems that arose from the lack of documentation regarding the bookpath and the related problems.
We'll add this crucial information to the README, fix the exception handling and look into the described problem with using the custom bookpath as soon as possible. 

We'll also look into your suggestion regarding the alternative directory structure as it sounds pretty reasonable and (as far as I can judge at the moment) nothing speaks against it.

Thanks again for your helpful feedback.

**Comment by bertsky** [comment]
> There's more to it. I cannot even get (my absolute path of the distribution's) `src/main/webapp/resources/books/` to work. I can only see the `LIBRARY` view without "oops" when I _don't_ set anything for `bookpath`. (It's always the same null pointer exception.)

I have instrumented `de.uniwue.web.io.FilePathManager`, and it shows me `/tmp/jetty-0.0.0.0-8080-Larex.war-_Larex-any-6878247102527668702.dir/webapp/resources/books` during `init()` when I make no use of a `bookpath` setting in larex.config. This path does not even exist! Yet, I do get the default `Test` book.

When I do set a `bookpath`, then `setLocalBooksPath()` will be invoked with the correct absolute path name on my system. But then I end up with the "ooopps" / NullPointerException from `LibraryController.home()` ← `new Library()` ← `new FileDatabase()` ← `FileDatabase.listBooks()` ← `FileDatabase.listBookFiles()`.

Is the web application perhaps running in some kind of jail/VM and I am thus restricted to some mem-mounted FS?

**Comment by bertsky** [comment]
> Is the web application perhaps running in some kind of jail/VM and I am thus restricted to some mem-mounted FS?

Confirmed. In the case of jetty, the bookpath **must** be underneath `jetty.home` (i.e. `/usr/share/jetty9`). This is quite impractical. This is on the system partition, so I cannot even symlink to my data, I'll have to copy them.

**Comment by maxnth** [comment]
While trying to fix this bug we had similar observations as you but sadly couldn't yet force LAREX to actually use the user-supplied book path when it's outside ```jetty.home``` or ```catalina.home```.
We now moved this issue to the top of our internal to-do list and hope to ship a fix within the next week. 

Please excuse this rather annoying bug and any inconveniences caused by it.
