### ISSUE TITLE
set up own LAREX webapp

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/LAREX#167]
Hello! Sorry for this beginner question, but I'm wondering if it'd very difficult to host my own LAREX webapp for collaborative GT production and postcorrection in a project context on a server accessible via the internet. Is the installation analogous to the one described in the readme?

Many thanks!

**Comment by maxnth** [comment]
The installation would indeed be analogous to the one described in the Readme.
Server related setup like port-forwarding/using a reverse proxy do work analogous to similar webapps hosted via tomcat.

If it would help you, we could supply a basic Dockerfile for hosting a LAREX instance as well.

**Comment by alexander-winkler** [comment]
Thanks! I guess that this will be a somewhat steep learning curve for me, but I'll give it a try.
