### ISSUE TITLE
import segmentation without `@type`

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#172]
When I open existing PAGE-XML files with standalone LAREX – yes, I have managed to get around #160 and #162 in a Docker build (so when I have time, we'll get to the bottom of this) – then the UI keeps showing an hourglass and I see these exceptions on the console:

```
	at org.primaresearch.dla.page.layout.physical.text.impl.TextRegion.getTextType(TextRegion.java:149)
	at de.uniwue.web.io.PageXMLReader.getPageAnnotations(PageXMLReader.java:99)
	at de.uniwue.web.io.PageXMLReader.loadPageAnnotationsFromDisc(PageXMLReader.java:208)
	at de.uniwue.web.controller.DataController.getAnnotations(DataController.java:94)
```

(This is with the prima-core-libs 1.4.02 repackaged in current master.)

The error goes away when I add `@type` annotations for the regions.

Again, this strikes me as overly restrictive.

**Comment by maxnth** [comment]
Allowing regions without a specified type and just displaying them as "undefined region" or something similar sounds like a good idea.
Thanks for the suggestion.

**Comment by maxnth** [comment]
Added in d6cd3daf4d365aed58ea612eabc4bac7c06d620d and should now work for both import and export.
Imported `TextRegions` without a subtype will be shown as `TextRegions` in LAREX (which is now available for choosing in the sidebar) and assigning this tag to any segment will export it as a `TextRegion` without a subtype as well
