### ISSUE TITLE
import segmentation respecting `@orientation`

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#173]
When I open existing PAGE-XML files with stand-alone LAREX, it does not deskew according to the `@orientation` angle annotated.

It's probably just a little more work manually (where you always have to draw polygons when you could live with rectangles), but for the automatic parts I guess these pages won't work well, will they?

I remember dimly that preprocessing is _prior_ to GT annotation work in the OCR4all process model. So will rotation (and internal coordinate transformation) ever be supported here in LAREX?

**Comment by bertsky** [comment]
Can I help with example images / PAGE files? Or any pointers into the code I would need to look at?

Is rotation according to `/PcGts/Page/@orientation` out of reach currently, or just around the corner?

**Comment by maxnth** [comment]
Importing segmentation respecting `@orientation` was merged in e42c83a. 

The aspect of segmenting images with an non-zero orientation still has to be addressed @chaddy314

**Comment by maxnth** [comment]
closed by #274
