### ISSUE TITLE
upgrade to prima-core-libs 1.5

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#174]
There is a new release 1.5 for https://github.com/PRImA-Research-Lab/prima-core-libs which supports PAGE-XML version `2019-07-15`.

Most important changes in the 2019-07-15 schema are:

> 
> 
> *	Added TextStyle to Page element (default text style for whole page)
> 
> *	Added "orientation" float attribute to Page element (skew for the whole page)
> 
> * Added underlineStyle attribute to TextStyleType (valid values: singleLine, doubleLine, other)

(So this is related to #173 – sorry, I did not realize before.)

Do you already have plans on upgrading the libraries, or can I even do it myself (perhaps by just replacing the `src/lib/repository/org/primaresearch/*/*.{jar,pom}`) and make a PR?

**Comment by maxnth** [comment]
We're currently working a release 0.3 for both OCR4all and LAREX and the latter's dev branch already uses builds of prima-core-libs based on a [commit](https://github.com/PRImA-Research-Lab/prima-core-libs/commit/ffb43f24dcedbb7f1c330d4ce3936877a3379fed) newer than 1.5 as that commit fixes a bug which in turn caused a bug in LAREX.

**Comment by bertsky** [comment]
Wow, thanks for your super-fast response!

Ok, that's great news, and I'll switch to `dev` for now then.
