### ISSUE TITLE
"Subtract mode" for textline rectangle selection

### ISSUE THREAD

**Issue by alexander-winkler** [OCR4all/LAREX#185]
Hello! After running the dummy segmentation and line segmentation, I often find myself in a situation where I have to cut off multiple polygons. Cf. e.g. the following
![select_mode](https://user-images.githubusercontent.com/52370148/83116909-b776a500-a0cc-11ea-8929-a580d2b61f8d.png)
 
A similar problem arises in the case of initials.
![select_mode_initials](https://user-images.githubusercontent.com/52370148/83116994-d07f5600-a0cc-11ea-9cc6-50c161269b95.png)

I am aware that this problem could be avoided by previously marking the regions in LAREX but this often is too time consuming.

A relatively handy work-around could maybe be a "subtract mode" (as in [GIMP](https://docs.gimp.org/en/gimp-tools-selection.html)): You just draw a polygon on the segmented page and this polygon gets subtracted from all other polygons that intersect. A function like this would considerably speed up my work.

Thank you very much for your great work!

**Comment by bertsky** [comment]
Same for me. However, I feel like the existing _cut line_ tool could also be used for that – if it worked for existing regions (as the _combine_ tool does), not merely as a guide for future autoseg.

**Comment by alexander-winkler** [comment]
Yes, the cut line tool would do the job in most cases, I guess. The polygon subtraction might be a tad more versatile, though. An interesting use case of the cut line function would be the manual line separation. I quite often get two lines recognized as one and it's rather cumbersome to 1) adapt the polygon to one of the lines, 2) draw a new polygon around line two, 3) add the new polygon to the reading order.

Speaking of reading order: I would very much welcome 1) either a way to manually rerun the reading order algorithm or 2) a behaviour that puts a newly created polygon not at the end, but rather guesses what the correct position must be in the reading order.

**Comment by maxnth** [comment]
>either a way to manually rerun the reading order algorithm

This should work with the `Auto generate a reading order` icon in the menu bar (marked in red in the screenshot).
![Screenshot_20200530_182119](https://user-images.githubusercontent.com/33344081/83333786-a5e6f600-a2a2-11ea-97f3-0529a94f8371.png)
>a behaviour that puts a newly created polygon not at the end, but rather guesses what the correct position must be in the reading order.

We're currently testing several segmentation algorithms for OCR4all/LAREX and some of them offer a bit more advanced automatic reading order calculation so maybe this problem will get solved somewhere in the future by integrating the aforementioned algorithms.

**Comment by maxnth** [comment]
Subtract rectangles and polygons for segments and text lines were added in branch [feature/subtract](https://github.com/OCR4all/LAREX/tree/feature/subtract).

The use cases described by @alexander-winkler ("normal" subtraction) and @bertsky (cutting segments/text lines without running segmentation) should both be covered by this (short video demonstration can be viewed [here](https://streamable.com/kvnd1o)).

If the implemented behavior differs from what you would expect from a subtract feature, feel free to report back.
