### ISSUE TITLE
avoid automatically switching to ReadingOrder editing

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#187]
For some reason, whenever I finish some action in `SEGMENTS` → `Regions` **on a region imported from PAGE-XML** – for example change the class – the UI will immediately switch over to `SEGMENTS` → `Reading Order` afterwards.

This is annoying and elusive: I would understand it if the region _did not_ have a position in ReadingOrder yet (as do newly created regions) in order to "fill the hole right away", but to summon this view when there is actually nothing to do feels strange. 

Is there anything I can do for mitigation? Can ReadingOrder editing be disabled complete (maybe in `larex.config`)?

**Comment by maxnth** [comment]
Opening the reading order collapsible when changing to another region type (except ImageRegion, which would change the RO by being removed from it) does indeed seem not that useful.

>Can ReadingOrder editing be disabled complete

Sadly not at the moment, but maybe it would make sense to add it in to the settings in the UI and make it saveable (related to #182).

**Comment by maxnth** [comment]
Added in branch [fix/readingOrderDisplay](fix/readingOrderDisplay).

The reading order and the "reading order menu" will now only be displayed on actions which alter the existing reading order (as in removes element from an existing reading order).

A switch was added to `Advanced Settings` in the sidebar to completely suppress the forced display of the reading order (menu), even when actions alter the reading order.

Will be added to master in the next minor release (probably 0.3.2) in the near future.

**Comment by bertsky** [comment]
This works fine in general – thanks!

However, I noticed that `ReadingOrder` still gets activated after using the undo button. (Plus I am not sure this works at all in `edit` mode instead of `segment`...)

**Comment by maxnth** [comment]
>I noticed that ReadingOrder still gets activated after using the undo button.

This should be fixed now.

>Plus I am not sure this works at all in edit mode instead of segment

Seems to work for me in both modes.
Any concrete examples where it doesn't work?

**Comment by bertsky** [comment]
> > I noticed that ReadingOrder still gets activated after using the undo button.
> 
> This should be fixed now.

It is – thanks a lot!



> > Plus I am not sure this works at all in edit mode instead of segment
> 
> Seems to work for me in both modes.
> Any concrete examples where it doesn't work?

No, cannot reproduce anymore. Maybe built the wrong version earlier. 

But in edit mode, all collapsible settings and regionSegmentationSettings are hidden, so I gathered the default `settings-hint-reading-order=checked` would be in effect. I guess there's another place I overlooked which controls this.

**Comment by maxnth** [comment]
The option for disabling/activating reading order hints is now displayed in `Edit` mode as well.
Fix was merged in dev and will therefore be included in the upcoming release.
