### ISSUE TITLE
Undo has no effect for auto-segment

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#189]
If I load an existing annotation and accidentally hit `segment` to wipe all segments and run automatic segmentation, then I cannot use `undo` to revert to the previous state.

**Comment by maxnth** [comment]
added in 8c3b17f4b89e7f31395bbc997c3e1a91f300dbd3

**Comment by maxnth** [comment]
Reverting to the loaded annotation (and undo for segmentation as a whole) should now be possible (since 8c3b17f4b89e7f31395bbc997c3e1a91f300dbd3)
