### ISSUE TITLE
page selection dropdown menu: highlight current

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#190]
The current implementation makes the dropdown menu for page selection somewhat ineffective: It does not highlight the page which is currently active, and one cannot just click out of the menu to make it disappear again. Thus, one is forced to jump somewhere and (unless one still remembers exactly the current page name) the current position gets lost.

**Comment by maxnth** [comment]
>It does not highlight the page which is currently active
Good idea, will get added.
>one cannot just click out of the menu to make it disappear again. Thus, one is forced to jump somewhere and (unless one still remembers exactly the current page name) the current position gets lost.
Clicking __anywhere__ but on the canvas or pressing the "ESC" key should work.
Deselect on canvas click will get added though.

**Comment by bertsky** [comment]
> Clicking **anywhere** but on the canvas or pressing the "ESC" key should work.

Ah, thanks!

**Comment by maxnth** [comment]
The page selection dropdown was reimplemented using Select2. The dropdown now highlights the currently selected page, allows "free text" search and is auto-adjusts its width to the longest file name.
