### ISSUE TITLE
edit segments: tool for moving a region

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#192]
I sometimes have (complex) polygons (from PAGE import) that have an offset against the canvas (e.g. from dewarped or deskewed pages). Then I have to manually drag each vertex to shift the whole region. This is both inprecise and tiresome.

So it would help to have yet another tool which allows **moving** an existing region (as in GIMP's "move selection").

Note: this could also be helpful as an auxiliary when two regions overlap heavily, and I want to edit them individually without having difficulty focussing (selecting) either one.

**Comment by bertsky** [comment]
@chreul just explained to me how to easily do this without an extra tool:

1. (select the region to edit)
1. holding `shift`, and clicking outside the region, drag a rectangle encompassing the whole region – this _selects all vertices_ together
1. click and drag to move the region as a whole

**Comment by maxnth** [comment]
dev now contains a mode for moving segments and textlines since 371bf5f949b4dca6f558a015d63aacc8dbff0fe0
