### ISSUE TITLE
`load existing segmentation` actually runs auto-segmentation

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#200]
https://github.com/OCR4all/LAREX/blob/27dc5bc9f263e5036a7d6dbcd9feeba5b2b1b832/src/main/webapp/resources/js/viewer/guiInput.js#L275

IMHO this should read: `_controller.loadAnnotations()`

**Comment by maxnth** [comment]
Thanks a lot for the hint.
Clicking `Load Now` should now actually load an existing annotation when the setting is activated.
