### ISSUE TITLE
regression in PAGE import

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#201]
A recent commit on `dev`, ce2df60db7908ef87158e16592cbb96ed69e29e4, brought (among many others) the following change to `web.io.FileDatabase`:

```diff
@@ -325,18 +313,8 @@ public class FileDatabase {
 	 * @return File name without extensions
 	 */
 	private String removeAllExtensions(String filename) {
-		if (passesSubFilter(filename)) {
-			final int extPointPos = filename.lastIndexOf(".");
-			final int subExtPointPos = filename.lastIndexOf(".", extPointPos - 1);
-			if(subExtPointPos > 0)
-				return filename.substring(0, subExtPointPos);
-			else
-				return filename.substring(0, extPointPos);
-		} else {
-			final int extensionPointer = filename.lastIndexOf(".");
-			if(extensionPointer > 0)
-				return filename.substring(0, extensionPointer);
-			
+		while(filename.contains(".")){
+			filename = FilenameUtils.getBaseName(filename);
 		}
 		return filename;
 	}
```

This effectively means that filenames must not contain dots anymore (except for the final one, separating the actual extension suffix)!

**Comment by maxnth** [comment]
Filenames are still allowed to contain multiple dots, the change to the function was done to secure that the basename is correctly extracted (`0001.bin.png` to `0001` instead of `0001.bin`). The loading of files directly shouldn't be affected by this change, only the display name of the page.
This is necessary for fixing loading and displaying several image variants of a page (e.g. nrm and png) when loading from a local book folder instead of a direct request from OCR4all (where it already works) in the future.

**Comment by bertsky** [comment]
> Filenames are still allowed to contain multiple dots

No, they are not. The code now just eats up everything after the first dot – see above!

> the change to the function was done to secure that the basename is correctly extracted (`0001.bin.png` to `0001` instead of `0001.bin`).

AFAICS that functionality (called _sub-extension_, and configurable via `imagefilter` setting in `larex.config` was working **before** the change. In the current code, `imagefilter` is ignored, and the new rule just happens to still match – but it is too broad.

> The loading of files directly shouldn't be affected by this change, only the display name of the page.

Oh, but it is!

https://github.com/OCR4all/LAREX/blob/27dc5bc9f263e5036a7d6dbcd9feeba5b2b1b832/src/main/java/de/uniwue/web/io/FileDatabase.java#L232

I **tested** this, bisecting the changes. With all recent git branching upstream (and _not merging_ #179 which I always need for my data), it took me a couple of hours to identify the above change (hidden in a mostly harmless larger changeset) as the cause.

> This is necessary for fixing loading and displaying several image variants of a page (e.g. nrm and png) when loading from a local book folder instead of a direct request from OCR4all (where it already works) in the future.

I doubt even this is correct. From my understanding, the previous state of affairs should have been perfectly capable of filtering sub-extensions as configured. If not, then please fix the problem _in the affected code branch_ (`passesSubFilter()`, `!imageSubFilter.isEmpty()`), but don't break all other use-cases.

**Comment by maxnth** [comment]
You're right, looked at it again and I must have mixed something terribly up.
Changes to the function were reverted in d5c2a2eacf4f25fd4bcd54de56636f93cfeb3dcf and pushed to dev.

Please excuse the problems caused by this.

**Comment by bertsky** [comment]
Thanks!
