### ISSUE TITLE
diff view prediction/GT

### ISSUE THREAD

**Issue by chreul** [OCR4all/LAREX#221]
in addition to "display prediction" it should be possible to activate a diff view which shows differences between the prediction and the GT using color coded insertions/deletions etc.
furthermore, it should be possible to hide lines with zero differences.

**Comment by bertsky** [comment]
Cf. https://github.com/hnesk/browse-ocrd/issues/13

**Comment by chreul** [comment]
thanks for the links and the provided thoughts! :-)
max, kevin: please have a closer look at this before before moving forward with implementing the new functionality. however, i hope that, at least for now, we will only need a somewhat tiny extension to the existing line-based view since we are only dealing with the most basic case, namely a alignment within single lines.

**Comment by maxnth** [comment]
added in 37091bbc0eb96651c03de298545f23aaa1c0d6ac
