### ISSUE TITLE
Manual line segmentation with TextRegion (no subtype)

### ISSUE THREAD

**Issue by b2m** [OCR4all/LAREX#224]
When trying manual line segmentation with `TextRegion` (no subtype) I receive the following message:

> Warning: Can only create TextLines if a TextRegion has been selected before hand.

**Expectation**: I would expect to be allowed using `TextRegion` without an explicit subtype (such as `paragraph` or `heading`).

**Version:** Larex was used via docker and the current ls6uniwue/ocr4all:**latest**.

**Comment by maxnth** [comment]
I just merged a fix for this into our staging branch and after the new release candidate is tested and approved it will be available in the upcoming release 0.5 of OCR4all/LAREX (which will be released in the next few days).

**Comment by b2m** [comment]
I was trying to reproduce the error using the current ls6uniwue/ocr4all:**nightly** docker image containing
 - OCR4All: 0.5-RC2
 - Larex: 0.5-RC3

As described the reported bug is no longer reproducible, and therefore considered fixed.

Thank you =)
