### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IlaCode** [OCR4all/LAREX#239]
Hi can you help me? 

![Immagine](https://user-images.githubusercontent.com/74908338/99957878-a90dfb00-2d88-11eb-8053-b8d99a3a015a.png)

**Comment by maxnth** [comment]
Hi, looks like you're using Java 14.0.2 to build LAREX but we currently still target Java 8 (we plan to upgrade the Java target when moving to Spring Boot 2  the future though).

**Comment by IlaCode** [comment]
Now it works, thanks!
