### ISSUE TITLE
Could not find artifact org.primaresearch:basic:jar:1.5a

### ISSUE THREAD

**Issue by exitNA** [OCR4all/LAREX#241]
hello:
when I try to build project, I came across the problem that i can't find org.primaresearch:basic:jar.
so, how can i get the dependicies ?

**Comment by maxnth** [comment]
Hi, the `prima-core-libs` are stored locally in the internal project repository (`src/lib/repository/...`).
Maven should automatically collect these dependencies as specified here in the `pom.xml`:
https://github.com/OCR4all/LAREX/blob/bc84b6125430288afedc071bf5b46a7469105258/pom.xml#L162-L165

We recently switched from v1.5a to v1.5b of the `prima-core-libs` so in case you pulled the latest master recently and your `pom.xml` didn't get updated this may be the cause of the problem.

Does building with a "clean" clone of the repositories master branch work?

**Comment by exitNA** [comment]
thanks
