### ISSUE TITLE
Text recognition

### ISSUE THREAD

**Issue by IlaCode** [OCR4all/LAREX#244]
I am trying to recognize the text of a historical book. After segmenting regions and selecting lines of text, doesn't it automatically recognize text? Can I just manually type the text? The book has 100 pages and I would like to speed up the process.

**Comment by maxnth** [comment]
>I am trying to recognize the text of a historical book. After segmenting regions and selecting lines of text, doesn't it automatically recognize text?

There's [OCR4all](https://github.com/OCR4all/OCR4all) for that.
OCR4all uses LAREX for certain workflow steps (region segmentation, post correction, ...) but additionally allows text prediction and model training.

**Comment by IlaCode** [comment]
Thanks a lot. Anyway I wanted to inform you that I followed the vbox installation guide, on windows 10 I can't reach the url (err_connection__timeout), but it works perfectly on my windows 7. See you soon!

**Comment by maxnth** [comment]
> Anyway I wanted to inform you that I followed the vbox installation guide, on windows 10 I can't reach the url (err_connection__timeout), but it works perfectly on my windows 7. See you soon!

Do other VBoxes (which also are accessible from the host through e.g. port forwarding) work for you on Windows 10?

**Comment by maxnth** [comment]
Feel free to reopen if the problem persists.
