### ISSUE TITLE
permissions on Larex docker

### ISSUE THREAD

**Issue by jthale76** [OCR4all/LAREX#256]
Hi Max, I tried the docker route and got an error saying pull access denied:

bash-3.2$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: jthale76
Password: 
Login Succeeded

bash-3.2$ docker pull mathnth/larex
Using default tag: latest
Error response from daemon: pull access denied for mathnth/larex, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by maxnth** [comment]
>bash-3.2$ docker pull mathnth/larex

Does `docker pull maxnth/larex` work?

**Comment by jthale76** [comment]
it works now!  thank you.
