### ISSUE TITLE
MetsReader and ImageLoader: support remote URLs

### ISSUE THREAD

**Issue by bertsky** [OCR4all/LAREX#329]
Since https://github.com/OCR4all/LAREX/commit/453ff15be0af23b3eb78823cd3e14efb438f5135, if the METS contains file references which are true URLs (not local file paths), then the library will not crash, but the respective book will be empty (and I cannot seem to leave such an empty book afterwards, I'll have to reload the page entirely).

It would be really helpful if LAREX was able to manage such remote files in a semi-transparent manner: 
- fetch them to a local path relative to the METS by converting the URL (stripping some predefined prefix and creating subdirectories as needed)
- when loading, use that local path
- (perhaps optionally, for PAGE files when saving, convert to a local reference)

**Comment by bertsky** [comment]
Oh, and I should mention that it would make perfect sense to coordinate this with the upcoming [OCR-D feature](https://github.com/OCR-D/core/issues/323) that multiple FLocat refs are allowed per file. This will enable keeping the original remote presentation links in addition to downloaded local paths (with sane file names), so after processing the temporary local refs can be converted back to public and removed.

So if LAREX supports URL refs, it should _also_ already support ignoring such remote refs if local refs are additionally present.

**Comment by bertsky** [comment]
> So if LAREX supports URL refs, it should _also_ already support ignoring such remote refs if local refs are additionally present.

Ok, judging by the [code](https://github.com/OCR4all/LAREX/blob/4f97126dac411abdfa6aa9b7f201b2e3c28ff70f/src/main/java/de/uniwue/web/io/MetsReader.java#L74-L87), this should currently work already (i.e. http FLocats will be ignored). 

I have also tested this successfully.

So nothing special needs to be done in LAREX after all – an **external** program could simply download all files of the required fileGrps and change them to local refs with sane file names (as `ocrd workspace find --download` does, but keeping the remote refs, as with [mm-update](https://github.com/slub/mets-mods2tei/pull/67/files/e9f3bdaec01f73df01452f46a73c64a03eaad9be..7226ba80a7b82b873376352a76e7a75420a9d5b3)).

What remains to be done is instruct users how to do so. (Currently, they'll simply be surprised to get an empty fileGrp list if everything is remote URLs.)

Should we leave this open as a **documentation** issue?

**Comment by bertsky** [comment]
Alas, it does not work on `dev` anymore!

If a file has a secondary remote FLocat, then it will not show up as page in the editor. (Despite the fact that it was activated in the library dialog.) So if _all_ files are formatted this way, then _no_ pages are shown.

My guess is that [this change](https://github.com/OCR4all/LAREX/commit/f9544c60a2cea98353439c1afc3b78d56690018e) is responsible.

**Comment by maxnth** [comment]
Argh that's annoying, we'll try to find some time to look into this issue (and some of the others like #240 ) in the following days / weeks.

**Comment by bertsky** [comment]
Any news on this? I'd really like to switch to the newest `dev` version because of the other fixes, but this breaking change is a show-stopper for me.

**Comment by maxnth** [comment]
Still on our backlog (I promise), sadly still didn't get to it yet. Will update as soon as we find some time (hopefully sooner than later).

**Comment by M3ssman** [comment]
@maxnth Have you considered to use a dedicated component for METS-handling, like [mets-model](https://github.com/MyCoRe-Org/mets-model)?

**Comment by maxnth** [comment]
>My guess is that [this change](https://github.com/OCR4all/LAREX/commit/f9544c60a2cea98353439c1afc3b78d56690018e) is responsible.

Finally got to looking into it, this indeed messed with loading annotations in METS projects. Starting from [70be72](https://github.com/OCR4all/LAREX/commit/070be7286b1802f436ad3c3861018ffdc2d1e299) this now works for me again  (and I cautiously hope for other's as well) while also allowing loading annotations from files with certain special characters in the file name (which the "fix" above was intended to solve).

**Comment by maxnth** [comment]
I'm gonna mark this as fixed, in case I missed something feel free to reopen this issue.
